version = 1

exclude_patterns = [".github/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "airbnb"
  plugins = ["react"]
  environment = ["nodejs"]
  dialect = "typescript"